### ISSUE TITLE
Implementar la clase que llamará al comando rake:test para iniciar la ejecución de pruebas

### ISSUE THREAD

**Issue by Lesfig** [rofaccess/tfg#5]
Detalle de implementación:
Nombe de la clase: Test
Métodos: run

Liri::Test.run(tests_folder)

Pasos:
- Probar ejecución de tests ya existentes de Liri
- Investigar como ejecutar tareas rake de los tests o ejecutar directamente los tests

**Comment by rofaccess** [comment]
Para probar, ejecutar
> bundle exec rspec spec/test_spec.rb
