### ISSUE TITLE
Procesar el resultado de la ejecución de pruebas

### ISSUE THREAD

**Issue by Lesfig** [rofaccess/tfg#6]
Detalle de implementación:
Nombre de clase: TestResult
metodos: show

**Comment by rofaccess** [comment]
Liri::Test.run ya ejecuta las pruebas usando rspec.
Ahora hay que procesar el resultado de rspec
Opciones:
1. Hacer que rspec devuelva el resultado en un archivo, leer el archivo e imprimirlo en pantalla.
2. Hacer que rspec devuelva el resultado en un archivo, leer el archivo y procesarlo para mostrarlo en nuestro propio formato
3. Inicializar de algun modo rspec y obtener la informacion del objeto.
